#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Ready. Set. Pack.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Bacon Labs                                
your_link                                 : https://baconlabs.org                     
your_city                                 :                                 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Where are you going?
    description                           : Start with creating a Trip. The amount of Items needed for your Trip will be calculated for you.
    fontawesome_icon_name                 : plane
    
  - title                                 : What do you bring?
    description                           : Items can be anything as a pair of Socks, a Charger or even your favorite Coffee Mug.
    fontawesome_icon_name                 : tshirt

  - title                                 : What goes together?
    description                           : Group a couple of Items together to pack them even easier in just one-single Tap.
    fontawesome_icon_name                 : shopping-bag

  - title                                 : What goes where?
    description                           : If you feel super organized, create Luggage and add your Items to it. Now or later.
    fontawesome_icon_name                 : suitcase

  - title                                 : Who are you going with?
    description                           : Traveling alone can be boring, so add your travel companions and assign them Items as well.
    fontawesome_icon_name                 : user-friends

  - title                                 : And who is travelling the most?
    description                           : Everyone loves a good challenge. Collect points for each travel and see what Status you can reach.
    fontawesome_icon_name                 : id-badge



# Theme Settings
topbar_color                              : "#D8552B"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#EED9C4"

link_color                                : "#D8552B"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#D8552B"
feature_icons_background_color            : "#FFEDD7"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#28282C"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

# baseurl: /bags
url: "https://bags.baconlabs.org"
